"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from zyg_py.types import BaseModel


class PostEventsResponseBodyTypedDict(TypedDict):
    r"""Event successfully created"""

    event_id: NotRequired[str]
    message: NotRequired[str]


class PostEventsResponseBody(BaseModel):
    r"""Event successfully created"""

    event_id: Annotated[Optional[str], pydantic.Field(alias="eventId")] = None

    message: Optional[str] = None
