workflowVersion: 1.0.0
sources:
    zyg-py-OAS:
        inputs:
            - location: ../playground/spec.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/zyghq/zyghq/zyg-py-oas
targets:
    zyg-py:
        target: python
        source: zyg-py-OAS
